# These resources should be a replacement for the following adhoc command

# helm template kube-prometheus prometheus-community/kube-prometheus-stack --include-crds \
#   | yq 'select(.kind == "CustomResourceDefinition") * {"metadata": {"annotations": {"meta.helm.sh/release-name": "kube-prometheus", "meta.helm.sh/release-namespace": "monitoring"}}}' \
#   | kubectl create -f - || true
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/prometheus-operator/prometheus-operator
  ref:
    tag: v0.87.0
  ignore: |
    /*
    !/example/prometheus-operator-crd
---
# Prometheus CRDs are needed for Service Monitor
# On Cilium CNI
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-crds
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: prometheus-operator-crds
  path: ./example/prometheus-operator-crd
  prune: false
  wait: true
  timeout: 5m
