apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/prometheus-operator/prometheus-operator
  ref:
    name: refs/heads/main
  ignore: |
    /*
    !/example/prometheus-operator-crd